const provinceItaliane = [
  { value: "agrigento", label: "Agrigento" },
  { value: "alessandria", label: "Alessandria" },
  { value: "ancona", label: "Ancona" },
  { value: "aosta", label: "Aosta" },
  { value: "arezzo", label: "Arezzo" },
  { value: "ascoli-piceno", label: "Ascoli Piceno" },
  { value: "asti", label: "Asti" },
  { value: "avellino", label: "Avellino" },
  { value: "bari", label: "Bari" },
  { value: "barletta-andria-trani", label: "Barletta-Andria-Trani" },
  { value: "belluno", label: "Belluno" },
  { value: "benevento", label: "Benevento" },
  { value: "bergamo", label: "Bergamo" },
  { value: "biella", label: "Biella" },
  { value: "bologna", label: "Bologna" },
  { value: "bolzano", label: "Bolzano" },
  { value: "brescia", label: "Brescia" },
  { value: "brindisi", label: "Brindisi" },
  { value: "cagliari", label: "Cagliari" },
  { value: "caltanissetta", label: "Caltanissetta" },
  { value: "campobasso", label: "Campobasso" },
  { value: "caserta", label: "Caserta" },
  { value: "catania", label: "Catania" },
  { value: "catanzaro", label: "Catanzaro" },
  { value: "chieti", label: "Chieti" },
  { value: "como", label: "Como" },
  { value: "cosenza", label: "Cosenza" },
  { value: "cremona", label: "Cremona" },
  { value: "crotone", label: "Crotone" },
  { value: "cuneo", label: "Cuneo" },
  { value: "enna", label: "Enna" },
  { value: "ferrara", label: "Ferrara" },
  { value: "firenze", label: "Firenze" },
  { value: "foggia", label: "Foggia" },
  { value: "forlì-cesena", label: "Forlì-Cesena" },
  { value: "frosinone", label: "Frosinone" },
  { value: "genova", label: "Genova" },
  { value: "gorizia", label: "Gorizia" },
  { value: "grosseto", label: "Grosseto" },
  { value: "imperia", label: "Imperia" },
  { value: "isernia", label: "Isernia" },
  { value: "la-spezia", label: "La Spezia" },
  { value: "l'aquila", label: "L'Aquila" },
  { value: "latina", label: "Latina" },
  { value: "lecce", label: "Lecce" },
  { value: "lecco", label: "Lecco" },
  { value: "livorno", label: "Livorno" },
  { value: "lodi", label: "Lodi" },
  { value: "lucca", label: "Lucca" },
  { value: "macerata", label: "Macerata" },
  { value: "mantova", label: "Mantova" },
  { value: "massa-carrara", label: "Massa-Carrara" },
  { value: "matera", label: "Matera" },
  { value: "messina", label: "Messina" },
  { value: "milano", label: "Milano" },
  { value: "modena", label: "Modena" },
  { value: "monza-brianza", label: "Monza e Brianza" },
  { value: "napoli", label: "Napoli" },
  { value: "novara", label: "Novara" },
  { value: "nuoro", label: "Nuoro" },
  { value: "oristano", label: "Oristano" },
  { value: "padova", label: "Padova" },
  { value: "palermo", label: "Palermo" },
  { value: "parma", label: "Parma" },
  { value: "pavia", label: "Pavia" },
  { value: "perugia", label: "Perugia" },
  { value: "pesaro-urbino", label: "Pesaro e Urbino" },
  { value: "pescara", label: "Pescara" },
  { value: "piacenza", label: "Piacenza" },
  { value: "pisa", label: "Pisa" },
  { value: "pistoia", label: "Pistoia" },
  { value: "pordenone", label: "Pordenone" },
  { value: "potenza", label: "Potenza" },
  { value: "prato", label: "Prato" },
  { value: "ragusa", label: "Ragusa" },
  { value: "ravenna", label: "Ravenna" },
  { value: "reggio-calabria", label: "Reggio Calabria" },
  { value: "reggio-emilia", label: "Reggio Emilia" },
  { value: "rieti", label: "Rieti" },
  { value: "rimini", label: "Rimini" },
  { value: "roma", label: "Roma" },
  { value: "rovigo", label: "Rovigo" },
  { value: "salerno", label: "Salerno" },
  { value: "sassari", label: "Sassari" },
  { value: "savona", label: "Savona" },
  { value: "siena", label: "Siena" },
  { value: "siracusa", label: "Siracusa" },
  { value: "sondrio", label: "Sondrio" },
  { value: "sud-sardegna", label: "Sud Sardegna" },
  { value: "taranto", label: "Taranto" },
  { value: "terni", label: "Terni" },
  { value: "torino", label: "Torino" },
  { value: "trapani", label: "Trapani" },
  { value: "trento", label: "Trento" },
  { value: "treviso", label: "Treviso" },
  { value: "trieste", label: "Trieste" },
  { value: "udine", label: "Udine" },
  { value: "varese", label: "Varese" },
  { value: "venezia", label: "Venezia" },
  { value: "verbania", label: "Verbania" },
  { value: "vercelli", label: "Vercelli" },
  { value: "verona", label: "Verona" },
  { value: "vibo-valentia", label: "Vibo Valentia" },
  { value: "vicenza", label: "Vicenza" },
  { value: "viterbo", label: "Viterbo" },
];

export default provinceItaliane;
